import { Platform, StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";

const IS_WEB = Platform.OS === "web";

export const styles = StyleSheet.create({
  whiteboardOuter: {
    flex: 1,
    paddingVertical: IS_WEB ? 16 : 0,
    paddingHorizontal: IS_WEB ? 24 : 0,
    alignItems: IS_WEB ? "center" : "stretch",
  },
  whiteboardCard: {
    width: "100%",
    maxWidth: IS_WEB ? 1200 : undefined,
    borderRadius: IS_WEB ? 16 : 0,
    backgroundColor: IS_WEB ? COLORS.white : "transparent",
    borderWidth: IS_WEB ? 1 : 0,
    borderColor: IS_WEB ? "#E5E5E5" : "transparent",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: IS_WEB ? 4 : 0 },
    shadowOpacity: IS_WEB ? 0.08 : 0,
    shadowRadius: IS_WEB ? 10 : 0,
    elevation: IS_WEB ? 4 : 0,
    overflow: IS_WEB ? "hidden" : "visible",
  },
  whiteboardToolbar: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 12,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    gap: 8,
  },
  whiteboardToolButton: {
    padding: 8,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
  },
  whiteboardToolButtonActive: {
    backgroundColor: COLORS.primary + "15",
  },
  whiteboardToolDivider: {
    width: 1,
    height: 24,
    backgroundColor: "#E5E5E5",
    marginHorizontal: 4,
  },
  colorPreview: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#E5E5E5",
  },
  whiteboardCanvasContainer: {
    flex: 1,
    width: "100%",
  },
  whiteboardCanvas: {
    flex: 1,
  },
  strokeOptionsContainer: {
    paddingHorizontal: 12,
    paddingVertical: 8,
    backgroundColor: COLORS.white,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
  },
  strokeOptionsLabel: {
    fontSize: 12,
    color: COLORS.gray,
    marginBottom: 4,
  },
  strokeColorsRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
  },
  strokeColorDot: {
    width: 20,
    height: 20,
    borderRadius: 10,
    borderWidth: 2,
    borderColor: "#E5E5E5",
  },
  strokeColorDotActive: {
    borderColor: COLORS.black,
    borderWidth: 3,
  },
  strokeWidthRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 8,
    marginTop: 4,
  },
  strokeWidthButton: {
    flex: 1,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E5E5",
    alignItems: "center",
    justifyContent: "center",
  },
  strokeWidthButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + "10",
  },
  strokeWidthPreview: {
    width: "80%",
    backgroundColor: COLORS.black,
    borderRadius: 4,
  },
  shapeMenuContainer: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 12,
    paddingVertical: 6,
    gap: 8,
    borderBottomWidth: 1,
    borderBottomColor: "#E5E5E5",
    backgroundColor: COLORS.white,
  },
  shapeMenuButton: {
    flexDirection: "row",
    alignItems: "center",
    gap: 4,
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#E5E5E5",
  },
  shapeMenuButtonActive: {
    borderColor: COLORS.primary,
    backgroundColor: COLORS.primary + "10",
  },
  shapeMenuText: {
    fontSize: 12,
    color: COLORS.gray,
  },
  modalOverlay: {
    position: "absolute",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    zIndex: 1000,
  },
  saveModal: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 24,
    width: IS_WEB ? 400 : "90%",
    maxWidth: 400,
  },
  saveModalTitle: {
    fontSize: 20,
    fontWeight: "700",
    color: COLORS.black,
    marginBottom: 8,
  },
  saveModalSubtitle: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 20,
    lineHeight: 20,
  },
  saveModalButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 12,
    paddingHorizontal: 24,
    borderRadius: 8,
    alignItems: "center",
  },
  saveModalButtonText: {
    color: COLORS.white,
    fontSize: 16,
    fontWeight: "600",
  },
  exportOptionsRow: {
    flexDirection: "row",
    justifyContent: "space-between",
    marginTop: 16,
    gap: 12,
  },
  exportButton: {
    flex: 1,
    backgroundColor: COLORS.primary + "15",
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: "center",
  },
  exportButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.primary,
  },
});

