import { Question } from '../types';

export const mockExamResponse: Question[] = [
  {
    question_id: 'q_001',
    question_text: 'Tính đạo hàm của hàm số f(x) = x^2 + 3x',
    topic_id: 1,
    bloom_level: 'apply',
    difficulty: 'medium',
    explanation: 'Sử dụng công thức đạo hàm cơ bản',
    source: 'Sách giáo khoa Toán 12',
    created_at: '2024-05-19T10:00:00Z',
    updated_at: '2024-05-19T10:00:00Z',
    choices: [
      {
        question_id: 'q_001',
        text: '2x+3',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_001',
        text: '2x+5',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_001',
        text: '2x+2',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_001',
        text: '2x+10',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_002',
    question_text: 'Tính tích phân của hàm số f(x) = 3x^2',
    topic_id: 2,
    bloom_level: 'apply',
    difficulty: 'medium',
    explanation: 'Sử dụng công thức tích phân cơ bản',
    source: 'Sách giáo khoa Toán 12',
    created_at: '2024-05-20T09:00:00Z',
    updated_at: '2024-05-20T09:00:00Z',
    choices: [
      {
        question_id: 'q_002',
        text: 'x^3 + C',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_002',
        text: '3x^3 + C',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_002',
        text: 'x^2 + C',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_002',
        text: 'x^3/3 + C',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_003',
    question_text: 'Giới hạn của hàm số lim(x→0) (sinx / x) bằng bao nhiêu?',
    topic_id: 3,
    bloom_level: 'remember',
    difficulty: 'easy',
    explanation: 'Công thức giới hạn lượng giác cơ bản',
    source: 'Sách giáo khoa Toán 11',
    created_at: '2024-05-21T09:00:00Z',
    updated_at: '2024-05-21T09:00:00Z',
    choices: [
      {
        question_id: 'q_003',
        text: '1',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_003',
        text: '0',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_003',
        text: '∞',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_003',
        text: '-1',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_004',
    question_text: 'Tính đạo hàm của hàm số f(x) = e^x',
    topic_id: 1,
    bloom_level: 'understand',
    difficulty: 'easy',
    explanation: 'Đạo hàm của hàm mũ e^x bằng chính nó',
    source: 'Sách giáo khoa Toán 12',
    created_at: '2024-05-21T10:00:00Z',
    updated_at: '2024-05-21T10:00:00Z',
    choices: [
      {
        question_id: 'q_004',
        text: 'e^x',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_004',
        text: 'x·e^x',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_004',
        text: '1',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_004',
        text: 'x',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_005',
    question_text: 'Tính ∫ cos(x) dx',
    topic_id: 2,
    bloom_level: 'apply',
    difficulty: 'easy',
    explanation: 'Tích phân cơ bản của cos(x)',
    source: 'Sách giáo khoa Toán 12',
    created_at: '2024-05-21T11:00:00Z',
    updated_at: '2024-05-21T11:00:00Z',
    choices: [
      {
        question_id: 'q_005',
        text: 'sin(x) + C',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_005',
        text: '-sin(x) + C',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_005',
        text: 'cos(x) + C',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_005',
        text: 'x·cos(x) + C',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_006',
    question_text: 'Giải phương trình: x^2 - 5x + 6 = 0',
    topic_id: 4,
    bloom_level: 'apply',
    difficulty: 'medium',
    explanation: 'Phân tích thành nhân tử',
    source: 'Sách giáo khoa Toán 10',
    created_at: '2024-05-22T09:00:00Z',
    updated_at: '2024-05-22T09:00:00Z',
    choices: [
      {
        question_id: 'q_006',
        text: 'x = 2, x = 3',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_006',
        text: 'x = -2, x = -3',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_006',
        text: 'x = 1, x = 6',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_006',
        text: 'x = 0, x = 6',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_007',
    question_text: 'Tính đạo hàm của hàm số f(x) = ln(x)',
    topic_id: 1,
    bloom_level: 'apply',
    difficulty: 'medium',
    explanation: 'Đạo hàm của ln(x) là 1/x',
    source: 'Sách giáo khoa Toán 12',
    created_at: '2024-05-22T10:00:00Z',
    updated_at: '2024-05-22T10:00:00Z',
    choices: [
      {
        question_id: 'q_007',
        text: '1/x',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_007',
        text: 'x',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_007',
        text: 'ln(x)',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_007',
        text: 'e^x',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_008',
    question_text: 'Cho ma trận A = [[1,2],[3,4]]. Tính det(A)',
    topic_id: 5,
    bloom_level: 'apply',
    difficulty: 'medium',
    explanation: 'det(A) = ad - bc',
    source: 'Sách giáo khoa Đại số tuyến tính',
    created_at: '2024-05-22T11:00:00Z',
    updated_at: '2024-05-22T11:00:00Z',
    choices: [
      {
        question_id: 'q_008',
        text: '-2',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_008',
        text: '2',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_008',
        text: '1',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_008',
        text: '-1',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
  {
    question_id: 'q_009',
    question_text:
      'Xác suất tung một đồng xu đồng chất được mặt ngửa là bao nhiêu?',
    topic_id: 6,
    bloom_level: 'remember',
    difficulty: 'easy',
    explanation: 'Xác suất cơ bản của phép thử đồng đều',
    source: 'Sách giáo khoa Toán 11',
    created_at: '2024-05-22T12:00:00Z',
    updated_at: '2024-05-22T12:00:00Z',
    choices: [
      {
        question_id: 'q_009',
        text: '1/2',
        choice_id: 1,
        label: 'A',
        is_correct: true,
        is_selected: null,
      },
      {
        question_id: 'q_009',
        text: '1/3',
        choice_id: 2,
        label: 'B',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_009',
        text: '1',
        choice_id: 3,
        label: 'C',
        is_correct: false,
        is_selected: null,
      },
      {
        question_id: 'q_009',
        text: '2/3',
        choice_id: 4,
        label: 'D',
        is_correct: false,
        is_selected: null,
      },
    ],
  },
];
