import { StyleSheet } from "react-native";
import { COLORS } from "../../../constants/colors";

export const styles = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },

  header: {
    minHeight: 60,
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    paddingHorizontal: 16,
    paddingBottom: 12,
    borderBottomWidth: 1,
    borderColor: COLORS.gray,
  },
  
  headerTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: COLORS.black,
  },

  card: {
    backgroundColor: COLORS.white,
    padding: 16,
    borderRadius: 12,
    marginBottom: 16,
    borderWidth: 1,
    borderColor: COLORS.borderGray,
  },
  cardCorrect: {
    borderColor: "#4CAF50",
    borderWidth: 2,
    backgroundColor: "#F1F8F4",
  },
  cardIncorrect: {
    borderColor: "#F44336",
    borderWidth: 2,
    backgroundColor: "#FFF5F5",
  },
  titleRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 6,
    justifyContent: "space-between",
  },
  statusBadge: {
    flexDirection: "row",
    alignItems: "center",
    paddingHorizontal: 8,
    paddingVertical: 4,
    borderRadius: 12,
    gap: 4,
  },
  statusCorrect: {
    backgroundColor: "#4CAF50",
  },
  statusIncorrect: {
    backgroundColor: "#F44336",
  },
  statusText: {
    color: COLORS.white,
    fontSize: 12,
    fontWeight: "600",
  },
  questionIndex: {
    fontSize: 14,
    fontWeight: "400",
    color: COLORS.black,
  },
  questionText: {
    fontSize: 16,
    fontWeight: "500",
    color: COLORS.black,
    marginBottom: 8,
  },
  answerSection: {
    marginTop: 12,
  },
  answerSectionTitle: {
    fontSize: 14,
    fontWeight: "600",
    color: COLORS.gray,
    marginBottom: 8,
  },
  answerBox: {
    flexDirection: "row",
    alignItems: "flex-start",
    padding: 12,
    borderRadius: 8,
    backgroundColor: COLORS.lightGray,
    borderWidth: 1,
    borderColor: COLORS.borderGray,
  },
  answerBoxCorrect: {
    backgroundColor: "#E8F5E9",
    borderColor: "#4CAF50",
  },
  answerBoxIncorrect: {
    backgroundColor: "#FFEBEE",
    borderColor: "#F44336",
  },
  answerLabel: {
    fontWeight: "600",
    fontSize: 16,
    marginRight: 8,
    color: COLORS.black,
  },
  answerText: {
    fontSize: 15,
    color: COLORS.black,
    flex: 1,
  },
  unansweredText: {
    fontSize: 14,
    color: COLORS.gray,
    fontStyle: "italic",
  },

  footer: {
    position: "absolute",
    bottom: 0,
    left: 0,
    right: 0,
    padding: 16,
    backgroundColor: COLORS.white,
    flexDirection: "row",
    justifyContent: "space-between",
    borderTopWidth: 1,
    borderColor: COLORS.gray,
  },
  btn: {
    flexDirection: "row",
    alignItems: "center",
    gap: 6,
    paddingVertical: 12,
    paddingHorizontal: 18,
    borderRadius: 8,
  },

  backBtn: {
    backgroundColor: COLORS.lightGray,
  },
  backText: {
    fontSize: 15,
    fontWeight: "500",
    color: COLORS.black,
  },

  submitBtn: {
    backgroundColor: COLORS.primary,
  },

  submitText: {
    fontSize: 15,
    fontWeight: "600",
    color: COLORS.white,
  },
  resultSummary: {
    padding: 16,
    backgroundColor: COLORS.lightGray,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.borderGray,
  },
  resultCard: {
    backgroundColor: COLORS.white,
    borderRadius: 12,
    padding: 16,
    marginBottom: 12,
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 2 },
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 3,
  },
  resultRow: {
    flexDirection: "row",
    alignItems: "center",
    gap: 16,
  },
  resultInfo: {
    flex: 1,
  },
  resultLabel: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 4,
  },
  resultValue: {
    fontSize: 32,
    fontWeight: "700",
    color: COLORS.primary,
  },
  statsRow: {
    flexDirection: "row",
    gap: 12,
  },
  statCard: {
    flex: 1,
    backgroundColor: COLORS.white,
    borderRadius: 8,
    padding: 12,
    alignItems: "center",
  },
  statValue: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.black,
    marginBottom: 4,
  },
  statLabel: {
    fontSize: 12,
    color: COLORS.gray,
  },
  sectionHeader: {
    paddingHorizontal: 16,
    paddingTop: 8,
    paddingBottom: 8,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.black,
  },
  modalOverlay: {
    flex: 1,
    backgroundColor: "rgba(0, 0, 0, 0.5)",
    justifyContent: "center",
    alignItems: "center",
    padding: 20,
  },
  successModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  successIconContainer: {
    marginBottom: 20,
  },
  successIconCircle: {
    width: 100,
    height: 100,
    borderRadius: 50,
    backgroundColor: "#E8F5E9",
    justifyContent: "center",
    alignItems: "center",
  },
  successTitle: {
    fontSize: 28,
    fontWeight: "700",
    color: COLORS.black,
    marginBottom: 12,
    textAlign: "center",
  },
  successMessage: {
    fontSize: 16,
    color: COLORS.gray,
    marginBottom: 24,
    textAlign: "center",
    lineHeight: 24,
  },
  successScoreContainer: {
    backgroundColor: "#F5F5F5",
    borderRadius: 16,
    padding: 20,
    width: "100%",
    alignItems: "center",
    marginBottom: 24,
  },
  successScoreLabel: {
    fontSize: 14,
    color: COLORS.gray,
    marginBottom: 8,
    fontWeight: "500",
  },
  successScoreValue: {
    fontSize: 48,
    fontWeight: "700",
    color: COLORS.primary,
  },
  successScoreMax: {
    fontSize: 32,
    color: COLORS.gray,
    fontWeight: "500",
  },
  successButton: {
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    paddingHorizontal: 48,
    borderRadius: 12,
    width: "100%",
    alignItems: "center",
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  successButtonText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
  },
  // Confirm Modal Styles
  confirmModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  confirmIconContainer: {
    marginBottom: 20,
  },
  confirmIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#E3F2FD",
    justifyContent: "center",
    alignItems: "center",
  },
  confirmTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.black,
    marginBottom: 12,
    textAlign: "center",
  },
  confirmMessage: {
    fontSize: 16,
    color: COLORS.gray,
    marginBottom: 32,
    textAlign: "center",
    lineHeight: 24,
  },
  confirmButtons: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
  },
  confirmCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.lightGray,
    alignItems: "center",
    justifyContent: "center",
  },
  confirmCancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.gray,
  },
  confirmSubmitButton: {
    flex: 1,
    backgroundColor: COLORS.primary,
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: COLORS.primary,
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  confirmSubmitText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
  },
  // Warning Modal Styles
  warningModalContent: {
    backgroundColor: COLORS.white,
    borderRadius: 24,
    padding: 32,
    width: "100%",
    maxWidth: 400,
    alignItems: "center",
    shadowColor: "#000",
    shadowOffset: { width: 0, height: 8 },
    shadowOpacity: 0.25,
    shadowRadius: 16,
    elevation: 10,
  },
  warningIconContainer: {
    marginBottom: 20,
  },
  warningIconCircle: {
    width: 80,
    height: 80,
    borderRadius: 40,
    backgroundColor: "#FFF3E0",
    justifyContent: "center",
    alignItems: "center",
  },
  warningTitle: {
    fontSize: 24,
    fontWeight: "700",
    color: COLORS.black,
    marginBottom: 12,
    textAlign: "center",
  },
  warningMessage: {
    fontSize: 16,
    color: COLORS.gray,
    marginBottom: 32,
    textAlign: "center",
    lineHeight: 24,
  },
  warningButtons: {
    flexDirection: "row",
    width: "100%",
    gap: 12,
  },
  warningCancelButton: {
    flex: 1,
    paddingVertical: 14,
    borderRadius: 12,
    borderWidth: 2,
    borderColor: COLORS.lightGray,
    alignItems: "center",
    justifyContent: "center",
  },
  warningCancelText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.gray,
  },
  warningSubmitButton: {
    flex: 1,
    backgroundColor: "#FF9800",
    paddingVertical: 14,
    borderRadius: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FF9800",
    shadowOffset: { width: 0, height: 4 },
    shadowOpacity: 0.3,
    shadowRadius: 8,
    elevation: 4,
  },
  warningSubmitText: {
    fontSize: 16,
    fontWeight: "600",
    color: COLORS.white,
  },
});